export const feeTypeDic = [
  { label: '租金', value: 'rent' },
  { label: '物业费', value: 'property' },
  { label: '管业管理费', value: 'management' },
  { label: '公摊费', value: 'public' },
  { label: '其他', value: 'other' },
];

export const payStatusDic = [
  { label: '未缴', value: '0' },
  { label: '已缴', value: '1' },
  { label: '逾期', value: '2' },
  { label: '部分缴纳', value: '3' },
];

export const tableOption = {
  height: 'auto',
  calcHeight: 220,
  tip: false,
  searchShow: true,
  searchIcon: true,
  searchIndex: 4,
  searchSpan: 6,
  searchMenuSpan: 6,
  border: true,
  index: true,
  selection: false,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  viewBtn: false,
  refreshBtn: false,
  columnBtn: true,
  menuWidth: 210,
  menuType: 'text',
  menuAlign: 'center',
  menuHeaderAlign: 'center',
  align: 'center',
  headerAlign: 'center',
  rowKey: 'paymentId',
  column: [
    {
      label: '账单编号',
      prop: 'paymentId',
      width: 150,
      slot: true,
      display: false,
    },
    {
      label: '合同编号',
      prop: 'contractNo',
      search: true,
      minWidth: 160,
      overHidden: true,
      display: false,
    },
    {
      label: '客户名称',
      prop: 'customerName',
      search: true,
      minWidth: 160,
      overHidden: true,
      display: false,
    },
    {
      label: '费用类型',
      prop: 'feeType',
      type: 'select',
      search: true,
      hide: true,
      dicData: feeTypeDic,
      display: false,
    },
    {
      label: '费用类型',
      prop: 'feeName',
      width: 120,
      display: false,
    },
    {
      label: '账期',
      prop: 'periodText',
      width: 210,
      slot: true,
      display: false,
    },
    {
      label: '应收金额',
      prop: 'amountDue',
      width: 120,
      align: 'right',
      headerAlign: 'right',
      slot: true,
      display: false,
    },
    {
      label: '实收金额',
      prop: 'amountPaid',
      width: 120,
      align: 'right',
      headerAlign: 'right',
      slot: true,
      display: false,
    },
    {
      label: '应缴日期',
      prop: 'payDeadline',
      width: 120,
      display: false,
    },
    {
      label: '缴费状态',
      prop: 'payStatus',
      type: 'select',
      dicData: payStatusDic,
      search: true,
      width: 110,
      slot: true,
      display: false,
    },
    {
      label: '催缴',
      prop: 'remindStatus',
      width: 150,
      slot: true,
      display: false,
    },
  ],
};
