-- 合同管理审批闭环 Flowable 流程记录表

CREATE TABLE IF NOT EXISTS `biz_contract_workflow_record` (
	`record_id` bigint NOT NULL AUTO_INCREMENT COMMENT '记录ID',
	`park_id` bigint NULL DEFAULT NULL COMMENT '园区ID',
	`business_type` varchar(64) NOT NULL COMMENT '业务类型',
	`business_key` varchar(64) NULL DEFAULT NULL COMMENT '业务主键',
	`process_def_key` varchar(128) NULL DEFAULT NULL COMMENT '流程定义Key',
	`process_def_id` varchar(128) NULL DEFAULT NULL COMMENT '流程定义ID',
	`process_name` varchar(200) NULL DEFAULT NULL COMMENT '流程名称',
	`process_ins_id` varchar(64) NULL DEFAULT NULL COMMENT '流程实例ID',
	`process_status` varchar(32) NULL DEFAULT NULL COMMENT '流程状态',
	`current_node_key` varchar(128) NULL DEFAULT NULL COMMENT '当前节点Key',
	`current_node` varchar(200) NULL DEFAULT NULL COMMENT '当前节点名称',
	`contract_id` bigint NULL DEFAULT NULL COMMENT '合同ID',
	`payment_id` bigint NULL DEFAULT NULL COMMENT '付款计划ID',
	`customer_id` bigint NULL DEFAULT NULL COMMENT '客户ID',
	`room_ids` varchar(500) NULL DEFAULT NULL COMMENT '房源ID集合',
	`template_key` varchar(128) NULL DEFAULT NULL COMMENT '打印模板Key',
	`form_key` varchar(128) NULL DEFAULT NULL COMMENT '内置表单Key',
	`form_data_json` longtext NULL COMMENT '表单数据快照',
	`attachment_json` longtext NULL COMMENT '附件数据',
	`print_file_url` varchar(500) NULL DEFAULT NULL COMMENT '打印文件地址',
	`approval_time` datetime NULL DEFAULT NULL COMMENT '审批完成时间',
	`remark` varchar(500) NULL DEFAULT NULL COMMENT '备注',
	`del_flag` char(1) NOT NULL DEFAULT '0' COMMENT '删除标志',
	`create_by` varchar(64) NULL DEFAULT NULL COMMENT '创建人',
	`create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
	`update_by` varchar(64) NULL DEFAULT NULL COMMENT '更新人',
	`update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
	PRIMARY KEY (`record_id`),
	KEY `idx_contract_wf_process` (`process_ins_id`),
	KEY `idx_contract_wf_contract_type` (`contract_id`, `business_type`, `del_flag`),
	KEY `idx_contract_wf_payment_type` (`payment_id`, `business_type`, `del_flag`),
	KEY `idx_contract_wf_status` (`business_type`, `process_status`, `del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同管理流程记录表';
