const statusDic = [
  {
    label: '启用',
    value: '0',
  },
  {
    label: '停用',
    value: '1',
  },
];

const rentUnitDic = [
  {
    label: '元/㎡/天',
    value: '元/㎡/天',
  },
  {
    label: '元/㎡/月',
    value: '元/㎡/月',
  },
];

const uploadProps = {
  res: 'data',
  url: 'link',
};

export const tableOption = {
  height: 'auto',
  calcHeight: 32,
  tip: false,
  header: true,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  selection: true,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  align: 'center',
  headerAlign: 'center',
  menuAlign: 'center',
  menuHeaderAlign: 'center',
  menuWidth: 150,
  viewBtn: false,
  addBtnText: '新增园区',
  editBtnText: '编辑',
  viewBtnText: '查看',
  dialogClickModal: false,
  labelWidth: 120,
  column: [
    {
      label: '园区名称',
      prop: 'name',
      minWidth: 160,
      search: true,
      rules: [
        {
          required: true,
          message: '请输入园区名称',
          trigger: 'blur',
        },
      ],
    },
    {
      label: '园区编码',
      prop: 'code',
      minWidth: 120,
      search: true,
    },
    {
      label: '状态',
      prop: 'status',
      type: 'select',
      dicData: statusDic,
      value: '0',
      width: 90,
      search: true,
      slot: true,
      rules: [
        {
          required: true,
          message: '请选择状态',
          trigger: 'change',
        },
      ],
    },
    {
      label: '管理面积(㎡)',
      prop: 'managementArea',
      align: 'center',
      headerAlign: 'center',
      width: 130,
      display: false,
    },
    {
      label: '可招商面积(㎡)',
      prop: 'rentableArea',
      align: 'center',
      headerAlign: 'center',
      width: 145,
      display: false,
    },
    {
      label: '总房源数',
      prop: 'totalRoomCount',
      align: 'center',
      headerAlign: 'center',
      width: 105,
      display: false,
    },
    {
      label: '可招商房源',
      prop: 'rentableRoomCount',
      align: 'center',
      headerAlign: 'center',
      width: 120,
      display: false,
    },
    {
      label: '园区总面积',
      prop: 'area',
      type: 'number',
      precision: 2,
      min: 0,
      hide: true,
    },
    {
      label: '园区总房间数',
      prop: 'totalRooms',
      type: 'number',
      precision: 0,
      min: 0,
      hide: true,
    },
    {
      label: '停车费',
      prop: 'parkingFee',
      type: 'number',
      precision: 2,
      min: 0,
      hide: true,
    },
    {
      label: '纬度',
      prop: 'latitude',
      type: 'number',
      precision: 6,
      min: -90,
      max: 90,
      hide: true,
    },
    {
      label: '经度',
      prop: 'longitude',
      type: 'number',
      precision: 6,
      min: -180,
      max: 180,
      hide: true,
    },
    {
      label: '租金范围(起)',
      prop: 'rentMin',
      type: 'number',
      precision: 2,
      min: 0,
      hide: true,
    },
    {
      label: '租金范围(止)',
      prop: 'rentMax',
      type: 'number',
      precision: 2,
      min: 0,
      hide: true,
    },
    {
      label: '租金单位',
      prop: 'rentUnit',
      type: 'select',
      dicData: rentUnitDic,
      value: '元/㎡/天',
      hide: true,
    },
    {
      label: '地区',
      prop: 'region',
      hide: true,
    },
    {
      label: '详细地址',
      prop: 'detailAddress',
      span: 24,
      hide: true,
    },
    {
      label: '园区小图',
      prop: 'thumbnailUrl',
      type: 'upload',
      listType: 'picture-img',
      dataType: 'string',
      action: '/blade-resource/oss/endpoint/put-file-attach',
      propsHttp: uploadProps,
      span: 24,
      hide: true,
    },
    {
      label: '园区Banner',
      prop: 'bannerUrl',
      type: 'upload',
      listType: 'picture-img',
      dataType: 'string',
      action: '/blade-resource/oss/endpoint/put-file-attach',
      propsHttp: uploadProps,
      span: 24,
      hide: true,
    },
    {
      label: '园区简介',
      prop: 'summary',
      type: 'textarea',
      minRows: 3,
      span: 24,
      hide: true,
    },
    {
      label: '配套服务',
      prop: 'supportingServices',
      type: 'textarea',
      minRows: 3,
      span: 24,
      hide: true,
    },
    {
      label: '交通信息',
      prop: 'trafficInfo',
      type: 'textarea',
      minRows: 3,
      span: 24,
      hide: true,
    },
    {
      label: '园区图文介绍',
      prop: 'content',
      component: 'avue-ueditor',
      action: '/blade-resource/oss/endpoint/put-file',
      propsHttp: uploadProps,
      minRows: 4,
      span: 24,
      hide: true,
    },
    {
      label: '联系人',
      prop: 'contactName',
      hide: true,
    },
    {
      label: '联系电话',
      prop: 'contactPhone',
      minWidth: 130,
    },
    {
      label: '备注',
      prop: 'memo',
      type: 'textarea',
      minRows: 3,
      span: 24,
      hide: true,
    },
  ],
};
