import { statusDic } from './contract';

export const paymentStatusDic = [
  { label: '未缴', value: '0' },
  { label: '已缴', value: '1' },
  { label: '逾期', value: '2' },
  { label: '部分缴纳', value: '3' },
];

export const changeTypeDic = [
  { label: '租金变更', value: 'rent' },
  { label: '租期变更', value: 'endDate' },
  { label: '其他变更', value: 'other' },
];

export const changeApprovalStatusDic = [
  { label: '草稿', value: '0' },
  { label: '待审批', value: '1' },
  { label: '已通过', value: '2' },
  { label: '已驳回', value: '3' },
];

export const terminationApprovalStatusDic = [
  { label: '草稿', value: 0 },
  { label: '待审批', value: 1 },
  { label: '已批准', value: 2 },
  { label: '已驳回', value: 3 },
];

export const terminationStatusDic = [
  { label: '待结算', value: 0 },
  { label: '已结算', value: 1 },
  { label: '已取消', value: 2 },
];

export const approvalStatusDic = [
  { label: '未发起', value: '' },
  { label: '审批中', value: 'running' },
  { label: '已通过', value: 'approved' },
  { label: '已驳回', value: 'rejected' },
  { label: '已取消', value: 'canceled' },
  { label: '已删除', value: 'deleted' },
];

export const tableOption = {
  tip: false,
  searchShow: true,
  searchSpan: 4,
  searchMenuSpan: 4,
  searchMenuPosition: 'left',
  searchLabelWidth: 80,
  border: true,
  index: true,
  addBtn: false,
  editBtn: false,
  delBtn: false,
  viewBtn: false,
  menuWidth: 180,
  align: 'center',
  headerAlign: 'center',
  column: [
    {
      label: '签订人名称',
      prop: 'customerName',
      search: true,
      searchLabelWidth: 90,
      searchWidth: 190,
      slot: true,
      minWidth: 220,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '开始日',
      prop: 'startDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 110,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '结束日',
      prop: 'endDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 110,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '租赁单价',
      prop: 'rentPrice',
      slot: true,
      width: 120,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '园区名称',
      prop: 'parkName',
      width: 120,
      align: 'center',
      headerAlign: 'center',
      showOverflowTooltip: true,
    },
    {
      label: '园区ID',
      prop: 'parkId',
      type: 'number',
      controls: false,
      hide: true,
    },
    {
      label: '房源信息',
      prop: 'roomName',
      width: 120,
      align: 'center',
      headerAlign: 'center',
      showOverflowTooltip: true,
    },
    {
      label: '签订日期',
      prop: 'signDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 110,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '总面积',
      prop: 'rentArea',
      slot: true,
      width: 100,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '合同编号',
      prop: 'contractNo',
      search: true,
      searchWidth: 190,
      slot: true,
      width: 160,
      align: 'center',
      headerAlign: 'center',
      showOverflowTooltip: true,
    },
    {
      label: '合同来源',
      prop: 'parentContractId',
      slot: true,
      width: 100,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '合同状态',
      prop: 'contractStatus',
      type: 'select',
      slot: true,
      dicData: statusDic,
      width: 150,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '退租时间',
      prop: 'terminationTime',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 110,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '物业单价',
      prop: 'propertyFee',
      slot: true,
      width: 120,
      align: 'center',
      headerAlign: 'center',
    },
    {
      label: '租赁保证金',
      prop: 'deposit',
      slot: true,
      width: 120,
      align: 'center',
      headerAlign: 'center',
    },
  ],
};
