export const statusDic = [
  { label: '待审批', value: '0' },
  { label: '生效', value: '1' },
  { label: '已到期', value: '2' },
  { label: '已续签', value: '3' },
  { label: '已退租', value: '4' },
  { label: '待盖章', value: '5' },
  { label: '退租中', value: '6' },
  { label: '退租交接中', value: '7' },
  { label: '房屋验收中', value: '8' },
];

export const paymentCycleDic = [
  { label: '月付', value: 'monthly' },
  { label: '季付', value: 'quarterly' },
  { label: '半年付', value: 'halfYear' },
  { label: '年付', value: 'yearly' },
];

export const paymentStatusDic = [
  { label: '未缴', value: '0' },
  { label: '已缴', value: '1' },
  { label: '逾期', value: '2' },
  { label: '部分缴纳', value: '3' },
];

export const tableOption = {
  height: 'auto',
  calcHeight: 170,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogWidth: 1080,
  dialogClickModal: false,
  menuWidth: 360,
  column: [
    {
      label: '合同编号',
      prop: 'contractNo',
      search: true,
      addDisplay: false,
      editDisplay: false,
      viewDisplay: true,
      width: 160,
    },
    {
      label: '合同名称',
      prop: 'contractName',
      search: true,
      minWidth: 180,
      span: 12,
      rules: [
        {
          required: true,
          message: '请输入合同名称',
          trigger: 'blur',
        },
      ],
    },
    {
      label: '客户ID',
      prop: 'customerId',
      type: 'number',
      controls: false,
      span: 12,
      hide: true,
    },
    {
      label: '客户名称',
      prop: 'customerName',
      search: true,
      minWidth: 150,
      span: 12,
    },
    {
      label: '园区ID',
      prop: 'parkId',
      type: 'number',
      controls: false,
      search: true,
      span: 12,
      rules: [
        {
          required: true,
          message: '请输入园区ID',
          trigger: 'blur',
        },
      ],
    },
    {
      label: '园区',
      prop: 'parkName',
      addDisplay: false,
      editDisplay: false,
      minWidth: 120,
    },
    {
      label: '楼宇ID',
      prop: 'buildingId',
      type: 'number',
      controls: false,
      span: 12,
      hide: true,
    },
    {
      label: '楼宇',
      prop: 'buildingName',
      minWidth: 120,
      span: 12,
    },
    {
      label: '房源ID',
      prop: 'roomId',
      type: 'number',
      controls: false,
      span: 12,
      hide: true,
    },
    {
      label: '房源',
      prop: 'roomName',
      search: true,
      minWidth: 140,
      span: 12,
    },
    {
      label: '状态',
      prop: 'contractStatus',
      type: 'select',
      search: true,
      slot: true,
      dicData: statusDic,
      width: 100,
      span: 12,
      value: '0',
    },
    {
      label: '租赁面积',
      prop: 'rentArea',
      type: 'number',
      controls: false,
      precision: 2,
      align: 'right',
      span: 12,
    },
    {
      label: '租金单价',
      prop: 'rentPrice',
      type: 'number',
      controls: false,
      precision: 2,
      align: 'right',
      span: 12,
    },
    {
      label: '月租金',
      prop: 'monthlyRent',
      type: 'number',
      controls: false,
      precision: 2,
      align: 'right',
      span: 12,
      rules: [
        {
          required: true,
          message: '请输入月租金',
          trigger: 'blur',
        },
      ],
    },
    {
      label: '物业费',
      prop: 'propertyFee',
      type: 'number',
      controls: false,
      precision: 2,
      align: 'right',
      span: 12,
      hide: true,
    },
    {
      label: '押金',
      prop: 'deposit',
      type: 'number',
      controls: false,
      precision: 2,
      align: 'right',
      span: 12,
    },
    {
      label: '开始日期',
      prop: 'startDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 120,
      span: 12,
      rules: [
        {
          required: true,
          message: '请选择开始日期',
          trigger: 'change',
        },
      ],
    },
    {
      label: '结束日期',
      prop: 'endDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      width: 120,
      span: 12,
      rules: [
        {
          required: true,
          message: '请选择结束日期',
          trigger: 'change',
        },
      ],
    },
    {
      label: '签约日期',
      prop: 'signDate',
      type: 'date',
      format: 'YYYY-MM-DD',
      valueFormat: 'YYYY-MM-DD',
      span: 12,
      hide: true,
    },
    {
      label: '缴费周期',
      prop: 'paymentCycle',
      type: 'select',
      dicData: paymentCycleDic,
      value: 'monthly',
      span: 12,
      hide: true,
    },
    {
      label: '提醒天数',
      prop: 'renewalRemindDays',
      type: 'number',
      controls: false,
      value: 30,
      span: 12,
      hide: true,
    },
    {
      label: '跟进人',
      prop: 'followUser',
      span: 12,
      hide: true,
    },
    {
      label: '管理费',
      prop: 'managementFee',
      type: 'number',
      controls: false,
      precision: 2,
      span: 12,
      hide: true,
    },
    {
      label: '公摊费',
      prop: 'publicFee',
      type: 'number',
      controls: false,
      precision: 2,
      span: 12,
      hide: true,
    },
    {
      label: '附件',
      prop: 'contractFileUrl',
      type: 'upload',
      action: '/blade-resource/oss/endpoint/put-file',
      listType: 'picture-img',
      propsHttp: {
        res: 'data',
        url: 'link',
      },
      dataType: 'string',
      limit: 1,
      span: 24,
      hide: true,
    },
    {
      label: '备注',
      prop: 'remark',
      type: 'textarea',
      minRows: 3,
      span: 24,
      hide: true,
    },
  ],
};
