export const tableOption = {
  height: 'auto',
  calcHeight: 32,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  viewBtn: true,
  selection: true,
  dialogWidth: 760,
  dialogClickModal: false,
  column: [
    {
      label: '费项名称',
      prop: 'name',
      search: true,
      rules: [
        {
          required: true,
          message: '请输入费项名称',
          trigger: 'blur',
        },
      ],
    },
    {
      label: '费项类型',
      prop: 'type',
      type: 'select',
      search: true,
      dicData: [
        { label: '系统费项', value: '0' },
        { label: '周期性费项', value: '1' },
        { label: '一次性费项', value: '2' },
      ],
      rules: [
        {
          required: true,
          message: '请选择费项类型',
          trigger: 'change',
        },
      ],
    },
    {
      label: '计量单位',
      prop: 'unitsCode',
      type: 'select',
      dicData: [
        { label: '度', value: '度' },
        { label: '平方米', value: '平方米' },
        { label: '吨', value: '吨' },
        { label: '立方米', value: '立方米' },
        { label: '千克', value: '千克' },
        { label: '元/月', value: '元/月' },
      ],
    },
    {
      label: '税率(%)',
      prop: 'taxFee',
      type: 'number',
      precision: 4,
      minRows: 0,
      controls: false,
      align: 'right',
    },
    {
      label: '启用',
      prop: 'isEnabled',
      type: 'switch',
      slot: true,
      width: 90,
      align: 'center',
      value: false,
      dicData: [
        { label: '停用', value: false },
        { label: '启用', value: true },
      ],
    },
    {
      label: '备注',
      prop: 'memo',
      type: 'textarea',
      minRows: 2,
      span: 24,
      hide: true,
    },
  ],
};
